# This file is used to configure Yarn settings for the project.
# For more information, see: https://yarnpkg.com/configuration/yarnrc

# This line fixes a bug in Yarn where the `node_modules` directory is not created or populated correctly.
nodeLinker: node-modules
